### ISSUE TITLE
[Bug]: Build broken since recent update (tmp vs extended attributes)

### ISSUE THREAD

**Issue by edlerd** [diddlesnaps/snapcraft-multiarch-action#17]
### What happened?

The recent update broke the build with this message.

```
Sorry, an error occurred in Snapcraft:
Unable to write extended attribute.

Recommended resolution:
Check that your filesystem supports extended attributes.

Detailed information:
Failed to write attribute 'user.snapcraft.origin_stage_package' on '/tmp/tmpddrm5kk5deb-extract/usr/share/man/man1/haproxy.1.gz'.
```

I am using the state-package feature of `snapcraft.yaml` as:

```
parts:
  python:
    plugin: python
    source: .
    stage-packages:
      - haproxy
```

It appears that snapcraft tries to write an extended attribute to a file in `/tmp`, which is not supported in the most recent diddledani/snapcraft:core20 image.

### What should have happened?

The build should have passed as before and extended attributes on `/tmp` should be supported in the docker image at `diddledani/snapcraft:core20`.

### Output of `snap info $snap_name`

```shell
not relevant for build step
```

### Output of `snap connections $snap_name`

```shell
not relevant for build step
```

### Output of `snap version`

```shell
not relevant for build step
```

**Comment by diddledani** [comment]
This should be fixed by the linked PR. It has finished building now and is available on Docker Hub - this action should automatically use it during your next GitHub Actions run.

**Comment by edlerd** [comment]
Can confirm it is fixed. Thank you for the quick response! 👍
