### ISSUE TITLE
arm64 Builds failing - cannot pack “/data/prime”: mksquashfs call failed: signal: segmentation fault (core dumped) Edit

### ISSUE THREAD

**Issue by samwiseg0** [diddlesnaps/snapcraft-multiarch-action#4]
Builds of arm64 have been failing with the error below. Builds of `amd64` and `armhf` seem unaffected with the same snapcraft.yaml file. This effects 2 projects that I work with.

The snapcraft build files can be found here:
https://github.com/sct/overseerr/blob/develop/snap/snapcraft.yaml
https://github.com/Tautulli/Tautulli/blob/master/snap/snapcraft.yaml

```
Sorry, an error occurred in Snapcraft:
Failed to create snap, snap command failed:
stdout:

stderr:
error: cannot pack "/data/prime": mksquashfs call failed: signal: segmentation fault (core dumped)

We would appreciate it if you anonymously reported this issue.
No other data than the traceback and the version of snapcraft in use will be sent.
Would you like to send this error data? (Yes/No/Always/View) [no]:
```

Could it be something with the build process?

**Comment by samwiseg0** [comment]
This issue seems to be related to QEMU. After reverting the last QEMU update. The build process works again. 
```
  - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt@sha256:df15403e06a03c2f461c1f7938b171fda34a5849eb63a70e2a2109ed5a778bde
```

**Comment by diddledan** [comment]
Interesting discovery.. I wonder what's changed in qemu...

**Comment by samwiseg0** [comment]
Agreed. That still does not rule out an issue with snapcraft though. It may be some incomparability that has now been introduced.
